config/routes.rb
Rails.application.routes.draw do
 
  resources :candidates

  root 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def index
    @candidates = Candidate.all
    
  end

  def new
    @candidate = Candidate.new

  end

  def create
    # debugger
    # clean_params = params.require(:candidate).permit(:name , :party , :age , :politics)
    
    @candidate = Candidate.new(candidates_params)
 
    if @candidate.save
      flash[:notic] = "新增成功!!!!!!!!!!!!" 
      redirect_to '/candidates'
    else
      render :new
    end

  end

  def show
   Candidate.find(params[:id])
  end

  def edit
  end

  def update
  end

  private
  def candidates_params
  clean_params = params.require(:candidate).permit(:name , :party , :age , :politics)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/index.html.erb
<h1>this is view</h1>

<%= flash[:notic] %><br>
<%= link_to '新增候選人' , 'candidates/new' %>

<table>
<tr>
  <td>name</td>
  <td>party</td>
  <td>age</td>
  <td>Action</td>
</tr>
<% @candidates.each do |candidate|%>
<tr>
  <td><%= link_to candidate.name , candidate_path(candidate) %></td>
  <td><%= candidate.party %></td>
  <td><%= candidate.age %></td>
  <td><%= link_to "編輯" , edit_candidate_path(candidate) %></td>
  <td><%= link_to "刪除" , candidate_path(candidate),method:"delete",data{confitm:"確定嗎？"} %></td>
</tr>
<% end %>
</table>

app/views/candidates/new.html.erb
<h1>add candidate</h1>

<!-- <form action="/candidates" method="POST">
  <input type="text" name="abc">
  <input type="submit" value="GO!" />
</form> -->

<%= form_for (@candidate) do |form| %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :party %>
  <%= form.text_field :party %>
</div>

<div>
  <%= form.label :age %>
  <%= form.text_field :age %>
</div>

<div>
  <%= form.label :politics %>
  <%= form.text_area :politics %>
</div>

<%= form.submit %>

<% end %>

app/views/candidates/show.html.erb
<h1>this is show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DIY1114</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>